spring.application.name=order-service
server.port=8084

spring.threads.virtual.enabled=true

# Database connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 4. Spring Cloud Stream Bindings for Event-Driven Messaging
# Bind the logical publisher 'orderSource' to the RabbitMQ destination 'order-events'
spring.cloud.function.definition=orderSource
spring.cloud.stream.bindings.orderSource-out-0.destination=order-events
spring.cloud.stream.bindings.orderSource-out-0.contentType=application/json
