spring.application.name=order-service
server.port=8084

spring.threads.virtual.enabled=true

# Database connection (PostgreSQL)
spring.datasource.url=${ORDER_DATASOURCE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari CP settings for Serverless Databases (Neon)
spring.datasource.hikari.max-lifetime=${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:600000}
spring.datasource.hikari.keepalive-time=${SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME:30000}
spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:2}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Feign client routing
cart.service.url=${CART_SERVICE_URL:http://localhost:8083}

# 3. RabbitMQ Configuration
spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES:amqp://guest:guest@localhost:5672}

# 4. Spring Cloud Stream Bindings for Event-Driven Messaging
spring.cloud.function.definition=orderSource;paymentEventsConsumer

# Config for outgoing Order events (published via StreamBridge)
spring.cloud.stream.bindings.orderSource-out-0.destination=order-events
spring.cloud.stream.bindings.orderSource-out-0.contentType=application/json

# Config for incoming Payment events (Saga Success / Rollback consumer)
spring.cloud.stream.bindings.paymentEventsConsumer-in-0.destination=payment-events
spring.cloud.stream.bindings.paymentEventsConsumer-in-0.group=order-payment-group
spring.cloud.stream.bindings.paymentEventsConsumer-in-0.contentType=application/json
